In [1]:
import os 
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pdb
from pyarrow import feather

#move up in directory
os.chdir('../')
# os.getcwd()

In [2]:
from helpers import dot2_

In [13]:
path_to_test_runs = 'data/rnn_raw_data/'

chakroun_file_name = 'data/human_raw_data/perc_corr_placebo_chakroun.csv'
wiehler_file_name = 'data/human_raw_data/perc_corr_gamblers_wiehler.csv'
rnn_data_file_name = 'lstm_a2c_nh_48_lr_0_0001_n_n_p_0_ew_0_05_vw_0_5_dr_0_5_res_d_f_p_0_1_rt_con_a_4_n_300_te_50000_id_{}_test_b_daw_p_{}'

In [31]:
## functions

# read human data
def get_human_data(file_name):
    df = pd.read_csv(file_name)
    return(df)
    
# read rnn data
walk = 1
id_ = 1
label = 'lstm + A2C EW linear'

def get_lstm_data(path_to_test_runs, rnn_data_file_name, label):
    
    acc = []
    walks = []
    
    for id_ in range(1,20):
        for walk in range1(1,4):
    
            df = pickle.load(open(path_to_test_runs + rnn_data_file_name.format(id_, walk), 'rb')) 
            acc.append(np.mean(df['accuracy']))
            walks.append(walk)
    
    labels = len(acc)*label
    
    return(acc, walk)

In [32]:
# read human data
wiehler_df = get_human_data(wiehler_file_name)
chakroun_df = get_human_data(chakroun_file_name)

In [ ]:
# read lstm data
acc = []
walk = []

for id_ in range(1,20):
    for walk in range1(1,4):

In [33]:
chakroun_df

    Unnamed: 0  rw_index  perc_corr
0            1         2   0.683333
1            2         1   0.586667
2            3         1   0.693333
3            4         1   0.670000
4            5         2   0.633333
5            6         2   0.720000
6            7         1   0.646667
7            8         3   0.683333
8            9         2   0.666667
9           10         1   0.533333
10          11         2   0.610000
11          12         3   0.433333
12          13         2   0.736667
13          14         3   0.723333
14          15         2   0.816667
15          16         3   0.553333
16          17         1   0.660000
17          18         1   0.693333
18          19         3   0.496667
19          20         3   0.566667
20          21         2   0.643333
21          22         2   0.703333
22          23         3   0.620000
23          24         1   0.570000
24          25         2   0.756667
25          26         3   0.436667
26          27         3   0.686667
27          28         1   0.710000
28          29         2   0.633333
29          30         3   0.690000
30          31         1   0.616667